directories:
  output: release/${version}
  buildResources: build
$schema: https://raw.githubusercontent.com/electron-userland/electron-builder/master/packages/app-builder-lib/scheme.json
appId: com.hifide.app
asar: true
asarUnpack:
  - node_modules/node-pty/build/Release/*.node
productName: HiFide
files:
  - filter:
      - dist
      - dist-electron
mac:
  target:
    - dmg
  icon: public/hifide-logo.png
  artifactName: ${productName}-Mac-${version}-Installer.${ext}
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/hifide-logo.png
  artifactName: ${productName}-Windows-${version}-Setup.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
linux:
  target:
    - AppImage
  icon: public/hifide-logo.png
  artifactName: ${productName}-Linux-${version}.${ext}
electronVersion: 38.2.1
